### ISSUE TITLE
How to include `.qmd` files?

### ISSUE THREAD

**Issue by TomBener** [pandoc-ext/include-files#1]
Thanks for the great Lua filter. I wonder if it is possible to include external Quarto files (`.qmd`)? It seems the current filter just includes external files as plain text, while the code chunk in Quarto files cannot be executed. Thanks in advance.

**Comment by cderv** [comment]
(Quarto team here 👋) 

I do think this is not a Lua filter problem - it is just that Lua filters are resolved and happens **after** code execution. So any .qmd content won't be processed. 

Using such filter works for any .qmd content that does not required to be processed before in Quarto processing. Code execution is what happens first before Pandoc is called in Quarto. 

We have the specific `include` shortcode syntax just for this : https://quarto.org/docs/authoring/includes.html 
It is not implemented in Lua for that matters because it would be too late for some feature.

**Comment by TomBener** [comment]
@cderv Thanks for clear explanation. I see it and will close the issue.
